<?php
namespace batsg\models;

use Yii;
use yii\base\Model;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;

/**
 * Model that has field $id, $data_status, $created_at, $created_by, $update_time, $updated_by.
 *
 * @property mixed $id
 * @property integer $data_status Record status. 1: new, 2: update, 9: delete.
 * @property mixed $created_by User id of creator.
 * @property integer $created_at Created timestamp.
 * @property mixed $updated_by User id of updator.
 * @property integer $updated_at Updated timestamp.
 *
 * @property string $createdAt Created date time.
 * @property string $updatedAt Created date time.
 * @property string $dataStatusStr
 */
class BaseBatsgModel extends BaseModel
{
    const DATA_STATUS_NEW = 1;
    const DATA_STATUS_UPDATE = 2;
    const DATA_STATUS_DELETE = 9;

    /**
     * If TRUE, generate UUID for ID.
     * If ID is generated by RDBMS automatically (for example, AUTO_INCREMENT in MySQL)
     * set $genUuid = FALSE.
     * @var boolean
     */
    public $genUuid = TRUE;

    /**
     * {@inheritDoc}
     * @see \yii\base\Component::behaviors()
     */
    public function behaviors()
    {
        return [
//             BlameableBehavior::className(),
            TimestampBehavior::className(),
        ];
    }

    /**
     * Perform massiveAssignment to a model.
     * @param CActiveRecord $model
     * @param array $parameters key=>value to assign to $model->attributes.
     * @param array $exclusiveFields Fields that are not assigned.
     */
//     public static function massiveAssign($model, $parameters,
//             $exclusiveFields = array('id', 'created_at', 'created_by', 'update_time', 'updated_by'))
//     {
//         parent::massiveAssign($model, $parameters, $exclusiveFields);
//     }

    /**
     * Get only valid models (data_status <> deleted) from model list.
     * @param BaseBatsgModel[] $modelList
     */
//     public static function getValidModels($modelList)
//     {
//         $result = array();
//         foreach ($modelList as $model) {
//             if ($model->data_status <> self::DATA_STATUS_DELETE) {
//                 $result[] = $model;
//             }
//         }
//         return $result;
//     }

    /**
     * Create ActiveQuery of finding records that are not deleted logically (data_status <> 9).
     * @return ActiveQuery
     */
    public static function findNotDeleted($condition = NULL, $params = []) {
        $result = static::find()->where(['OR', 'data_status IS NULL', ['!=', 'data_status', self::DATA_STATUS_DELETE]]);
        if ($condition) {
            $result = $result->where($condition, $params);
        }
        return $result;
    }

    /**
     * Find all records that are not deleted logically (data_status <> 9).
     * @return Model[] Array of caller class objects.
     */
    public static function findAllNotDeleted()
    {
        return self::findNotDeleted()->all();
    }

    /**
     * Reset fields below to NULL.
     *     id
     *     data_status
     *     created_at
     *     created_by
     *     update_time
     *     updated_by
     */
    public function resetCommonFields()
    {
        $this->setFieldToNull(array('id', 'data_status', 'created_at', 'created_by', 'update_time', 'updated_by'));
    }

    public function deleteLogically()
    {
        $this->data_status = self::DATA_STATUS_DELETE;
        if (!$this->save()) {
            $this->logError();
            throw new Exception("Error while deleting " . $this);
        }
    }

    /**
     * Generate unique string to be used as primary key.
     * @param string $prefix
     * @return string
     */
    public function generateId($prefix = NULL)
    {
        return $this->generateUniqueRandomString('id', $prefix);
    }

    /**
     * created_at in date time format.
     * @return string
     */
    public function getCreatedAt()
    {
        return \Yii::$app->formatter->asDatetime($this->created_at);
    }

    /**
     * updated_at in date time format.
     * @return string
     */
    public function getUpdatedAt()
    {
        return \Yii::$app->formatter->asDatetime($this->updated_at);
    }

    /**
     * Generate id for new record.
     * {@inheritDoc}
     * @see \yii\base\Model::beforeValidate()
     */
    public function beforeSave($insert)
    {
        $result = parent::beforeSave($insert);
        if ($result && $this->isNewRecord && $this->genUuid) {
            // Set id.
            $this->id = $this->generateId((new \ReflectionClass($this))->getShortName() . '-');
        }
        return $result;
    }

    /**
     * Add <em>data_status <> 9</em> (not deleted) condition to a query.
     * @param ActiveQuery $query
     */
    public static function addWhereNotDeleted(ActiveQuery $query)
    {
        $query->andWhere(['<>', static::tableName() . '.data_status', self::DATA_STATUS_DELETE]);
    }

    /**
     * @return string
     */
    public function getDataStatusStr()
    {
        return ArrayHelper::getValue(static::dataStatusOptionArr(), $this->data_status);
    }

    /**
     * @return string[]
     */
    public static function dataStatusOptionArr()
    {
        return [
            self::DATA_STATUS_NEW => '新規',
            self::DATA_STATUS_UPDATE => '変更',
            self::DATA_STATUS_DELETE => '削除',
        ];
    }
}
?>